### ISSUE TITLE
update user, status, docname info with AJAX

### ISSUE THREAD

**Issue by zangsir** [zangsir/coptic-xml-tool#5]
Currently updating user,status,docname info is possible and functioning without AJAX. A downside of this might be the resetting to the top of the page in the editor when reloading. This may not be desirable. We may instead use AJAX to implement this in the future.

**Comment by amir-zeldes** [comment]
Using AJAX is not strictly necessary, and it's fine also if the page jumps to the top. The only thing we need to avoid is this:

User edits text
User edits docname
User clicks update docname
Page reloads and edits to text are lost

We can deal with this using either warnings via JS ("you have unsaved work...") or by updating both (rename the button "Change and Save")

**Comment by zangsir** [comment]
It seems like I have already taken care of this - edited text is not lost even when you didn't save and clicked for example, update docname
