### ISSUE TITLE
add meta

### ISSUE THREAD

**Issue by zangsir** [zangsir/coptic-xml-tool#6]
We still need to add the meta data table and allow editing and updating the meta information.

**Comment by zangsir** [comment]
do we want the key field in the key, value pair to have unique values in the meta table?

**Comment by zangsir** [comment]
when the user adds the meta information into the document, is there a standard shared list of keys (e.g., year, volume, etc.), or the user should just enter key and values freely?

**Comment by amir-zeldes** [comment]
Yes, key-value pairs should be unique, so when entering an already existing key, the user should be warned via javascript (Metadatum X already exists. Are you sure you want to overwrite it?), then it should overwrite the value. In the database, values should be unique (replace on insert if exists).

**Comment by amir-zeldes** [comment]
There is a list of standard keys that can be suggested, but it should also be possible to type in new values.  We can do this with a `<datalist>` element.

**Comment by amir-zeldes** [comment]
The list of recommended metadata keys is at the bottom half of this page (ignore the annotation names in the top half, they are not metadata):

http://wiki.copticscriptorium.org/doku.php?id=annotation_layer_names

**Comment by zangsir** [comment]
meta functionality addressed in commit: https://github.com/zangsir/coptic-xml-tool/commit/807567f8506b3eb1938e73f42e5a72b25bf2cceb

including in this commit:
1. created metadata table in the db;
2. meta data associated with the document will be displayed in the editing page for a particular doc, below the editor window;
3. user can add meta pairs (key value) through a popup window and will immediately see the updated metadata list associated with the document after submitting;
4. user can delete meta pairs;

**NEXT:
1. Key-value pairs should be unique;
2. Implement a <datalist> element to suggest legitimate metadata keys.**

**Comment by zangsir** [comment]
added datalist support for the popup window for adding meta data. The options are generated by a generic make_options function that reads the metadata_fields.tab file that lists all the valid key names. However, there is still one problem: this list is long (40 items) and if the entire list doesn't fit on the screen vertically when dropped down, there is no scroll bar support for the datalist currently (this is also the case from searching online, where people say there is no scroll bar support for datalist, and also it's the same with the demo at the W3Schools tutorial (http://www.w3schools.com/html/tryit.asp?filename=tryhtml_elem_datalist). I am not sure if we'll be able to do something with CSS>

**Comment by zangsir** [comment]
Uniqueness of metadata key is addressed in commit https://github.com/zangsir/coptic-xml-tool/commit/4e109008824aded2b416f63502081e62d32b711e. 

Now the only possible thing left to do is to warn user.(but it is not absolutely necessary)

**Comment by amir-zeldes** [comment]
OK, I understand about too many values; you can skip this for now, I think a javascript auto-complete solution with top N candidates may be the best answer here (rather than a drop down).
